// Auth action types
export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_CHECK = "AUTH_CHECK"
export const LOGOUT = "LOGOUT"

// Ticket action types
export const FETCH_TICKETS_START = "FETCH_TICKETS_START"
export const FETCH_TICKETS_SUCCESS = "FETCH_TICKETS_SUCCESS"
export const FETCH_TICKETS_FAIL = "FETCH_TICKETS_FAIL"
export const CREATE_TICKET_START = "CREATE_TICKET_START"
export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS"
export const CREATE_TICKET_FAIL = "CREATE_TICKET_FAIL"
export const UPDATE_TICKET_STATUS_START = "UPDATE_TICKET_STATUS_START"
export const UPDATE_TICKET_STATUS_SUCCESS = "UPDATE_TICKET_STATUS_SUCCESS"
export const UPDATE_TICKET_STATUS_FAIL = "UPDATE_TICKET_STATUS_FAIL"

